### ISSUE TITLE
Another question about Gin start(Symbol not found: _luaL_setfuncs)

### ISSUE THREAD

**Issue by idevz** [ostinelli/gin#24]
Hi Ostinelli Yestoday I run Gin base the Lua and Luarocks was intalled from their Source Code not Brew install like Your Gin Doc, It works except the busted, So today I remove those Lua,Luarocks,Gin,and reinstall them as [Your Doc](http://gin.io/docs/install.html)
that I got a mistake like this:

```
2015/08/12 19:02:40 [error] 12773#0: *1 lua entry thread aborted: runtime error: error loading module 'cjson' from file '/usr/local/lib/lua/5.2/cjson.so':
	dlopen(/usr/local/lib/lua/5.2/cjson.so, 6): Symbol not found: _luaL_setfuncs
  Referenced from: /usr/local/lib/lua/5.2/cjson.so
  Expected in: dynamic lookup

stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(development-nginx.conf:39):1: in function <content_by_lua(development-nginx.conf:39):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:7200"
2015/08/12 19:02:41 [error] 12773#0: *2 lua entry thread aborted: runtime error: error loading module 'cjson' from file '/usr/local/lib/lua/5.2/cjson.so':
	dlopen(/usr/local/lib/lua/5.2/cjson.so, 6): Symbol not found: _luaL_setfuncs
  Referenced from: /usr/local/lib/lua/5.2/cjson.so
  Expected in: dynamic lookup

stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(development-nginx.conf:39):1: in function <content_by_lua(development-nginx.conf:39):1>, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:7200", referrer: "http://localhost:7200/"
```
here My question is That openresty runs base on LuaJIT, LuaJIT use the lua 5.1 ABI, but Gin is base on lua 5.2, luaL_setfuncs is a ABI of Lua 5.2,  so how to fix this?

**Comment by leite** [comment]
sorry, but your env is messed up since it is using Lua 5.2 and gin rockspec says it is Lua 5.1 only!

as you stated, gin installation guide uses lua package from brew repositories, as I can see lua package was upgraded to version 5.2 roughly 12 months ago.

I cannot confirm this (since I do not own a macintosh), but I think your luarocks installation is using your local lua (5.2) not luajit vm.

you should consider using luajit only or luajit with lua51 packages together.

please let us now if it works, if so documentation need to be upgraded :D

**Comment by istr** [comment]
+1 for @leite s comment

**Comment by idevz** [comment]
it's a lua version problem, use lua5.1 will fix this, @leite you mean gin base on lua5.1? but in the [[rockspec]](https://raw.githubusercontent.com/ostinelli/gin/master/gin-0.1.5-1.rockspec), it says 
```
dependencies = {
    "lua = 5.2",
```

**Comment by leite** [comment]
sure @idevz  it is Lua 5.2 sorry :|

but openresty is Lua 5.1 (luajit) and not compatible with Lua 5.2 and agentzh made that clear in [#204](https://github.com/openresty/lua-nginx-module/issues/204), [#343](https://github.com/openresty/lua-nginx-module/issues/343) and [#354](https://github.com/openresty/lua-nginx-module/issues/354)

I set up a fork with busted 2 and make that work with Lua 5.2, see: [travis/leite/gin](https://travis-ci.org/leite/gin) and I'm afraid it wont interop with openresty.

@ostinelli should switch to Lua 5.1 or remove it as proposed in #27.

**Comment by istr** [comment]
Still having ```>= 5.1``` [in my fork](https://github.com/ostinelli/gin/compare/master...istr:master), but @leite is right: in reality only ``` = 5.1 ``` could interoperate with OpenRESTY. I never realized that, though, because I am using a custom build (using LuaJIT only and a non-global luarocks setup), [like agentzh does](https://github.com/openresty/lua-nginx-module/issues/343#issuecomment-36433261).

**Comment by idevz** [comment]
yes, Base on Luajit Openresty get such a highly performance, and Luajit base on lua5.1, thus Gin is better to use only lua5.1.

**Comment by ostinelli** [comment]
Thank you all for this contribution.

**Comment by ostinelli** [comment]
Update the [installation docs](http://gin.io/docs/install.html).
